---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-monaco-service
  namespace: keptn
  labels:
    "app": "keptn"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-monaco-service-secrets
  namespace: keptn
  labels:
    "app": "keptn"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-monaco-service-secrets
  namespace: keptn
  labels:
    "app": "keptn"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-monaco-service-secrets
subjects:
  - kind: ServiceAccount
    name: keptn-monaco-service
---
# Deployment of our monaco-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monaco-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: monaco-service
  replicas: 1
  template:
    metadata:
      labels:
        run: monaco-service
        app.kubernetes.io/name: monaco-service
        app.kubernetes.io/version: 0.8.4
    spec:
      containers:
        - name: monaco-service
          image: keptnsandbox/monaco-service:0.8.4
          ports:
            - containerPort: 8080
          env:
            - name: MONACO_VERBOSE_MODE
              value: "true"
            - name: MONACO_DRYRUN
              value: "true"
            - name: MONACO_KEEP_TEMP_DIR
              value: "false"
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
        - name: distributor
          image: keptn/distributor:0.8.4
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "25m"
            limits:
              memory: "32Mi"
              cpu: "50m"
          env:
            - name: VERSION
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''app.kubernetes.io/version'']'
            - name: K8S_DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''app.kubernetes.io/name'']'
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName            
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.>'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
      serviceAccountName: keptn-monaco-service
---
# Expose monaco-service via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: monaco-service
  namespace: keptn
  labels:
    run: monaco-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: monaco-service

